### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by CaptainBlank7** [Gab351/Anuken-Mindustry#5]
GdxRuntime: Couldn't create window
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createGlfwWindow(Lwjgl3Application.java:445)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:391)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.createWindow(Lwjgl3Application.java:379)
com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:108)
io.anuke.mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:27)

**Comment by NQUARE** [comment]
I have this problem too. Help please!
